version: '3'
services:
  webserver:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${ROOT}/webpage:/var/www
      - ${ROOT}/Config/nginx/logs:/var/log/nginx
      - ${ROOT}/Config/nginx/conf.d/:/etc/nginx/conf.d
    links:
      - php
    networks:
      - webserver-network

  php:
    container_name: php
    #image: php:7-fpm
    build: ${ROOT}/Config/php
    restart: unless-stopped
    volumes:
      - ${ROOT}/webpage:/var/www
    networks:
      - webserver-network

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - webserver-network

  sql:
    container_name: sql
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: resume
      MYSQL_ROOT_PASSWORD: your_sql_password
    volumes:
      - ${ROOT}/Config/sql/data:/var/lib/mysql
    networks:
      - webserver-network

networks:
  webserver-network:
    driver: bridge