version: '3'
services:
  webserver:
    container_name: webserver
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${ROOT}/webpage:/var/www
      - ${ROOT}/Config/nginx/logs:/var/log/nginx
      - ${ROOT}/Config/nginx/conf.d/:/etc/nginx/conf.d
  php:
    container_name: php
    image: php:7-fpm
    restart: unless-stopped
    volumes:
      - ${ROOT}/webpage:/var/www